### ISSUE TITLE
Mixed code between IgniteStarter and IgniteSamples

### ISSUE THREAD

**Issue by eLud** [twostraws/IgniteStarter#1]
Nice job here Paul! But it seems that there is some mixing between IgniteStarter and IgniteSample codes.

The Starter repo references many of the files used in the Sample, for example in [Home.swift](https://github.com/twostraws/IgniteStarter/blob/main/Sources/Pages/Home.swift) and [Site.swift](https://github.com/twostraws/IgniteStarter/blob/main/Sources/Site.swift).

Nothing hard to fix for someone who wants to try, but you may want to clean it!

**Comment by piotrekjeremicz** [comment]
I prepared a PR #2 that includes a cleaned version of the project, which is built immediately after downloading. 

@eLud, if you have any comments or ideas, let me know, I will add to the branch. 😊

**Comment by twostraws** [comment]
This is now resolved thanks to @piotrekjeremicz 🙌
